// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxKoNuYIojBUrxSxwNlUsm0p4N6jPSLxw',
    appId: '1:729282474795:web:360c9b6cde62d6e7898b6e',
    messagingSenderId: '729282474795',
    projectId: 'deteksipohonkelapa',
    authDomain: 'deteksipohonkelapa.firebaseapp.com',
    storageBucket: 'deteksipohonkelapa.firebasestorage.app',
    measurementId: 'G-59Z3PYC7DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUz-WrTy_8oFbHkOYahWcwTJqNcJ7oV3s',
    appId: '1:729282474795:android:86b9e6472fef9d66898b6e',
    messagingSenderId: '729282474795',
    projectId: 'deteksipohonkelapa',
    storageBucket: 'deteksipohonkelapa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIYoJF1gOLCfVrCogb0-bkTC-eDwrN49c',
    appId: '1:729282474795:ios:ad2a1c380cfbc6e5898b6e',
    messagingSenderId: '729282474795',
    projectId: 'deteksipohonkelapa',
    storageBucket: 'deteksipohonkelapa.firebasestorage.app',
    androidClientId: '729282474795-m85a1dsehj1boo3r5pllokrk2t2s0nne.apps.googleusercontent.com',
    iosClientId: '729282474795-f8ctqn06jgqa1kdvs2ugj6ptnhokfrlu.apps.googleusercontent.com',
    iosBundleId: 'com.example.palmDiagnose',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIYoJF1gOLCfVrCogb0-bkTC-eDwrN49c',
    appId: '1:729282474795:ios:ad2a1c380cfbc6e5898b6e',
    messagingSenderId: '729282474795',
    projectId: 'deteksipohonkelapa',
    storageBucket: 'deteksipohonkelapa.firebasestorage.app',
    androidClientId: '729282474795-m85a1dsehj1boo3r5pllokrk2t2s0nne.apps.googleusercontent.com',
    iosClientId: '729282474795-f8ctqn06jgqa1kdvs2ugj6ptnhokfrlu.apps.googleusercontent.com',
    iosBundleId: 'com.example.palmDiagnose',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxKoNuYIojBUrxSxwNlUsm0p4N6jPSLxw',
    appId: '1:729282474795:web:d6c028077cf55cbb898b6e',
    messagingSenderId: '729282474795',
    projectId: 'deteksipohonkelapa',
    authDomain: 'deteksipohonkelapa.firebaseapp.com',
    storageBucket: 'deteksipohonkelapa.firebasestorage.app',
    measurementId: 'G-XFXZD6EDJM',
  );
}
